### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by Lutong-Qin** [Lab-LVM/imagenet-models#1]
Hello, author. Thank you for your excellent work. I encountered some difficulties while reproducing it. It seems that your model is not included in the TIMM library. Could you please confirm if you have added them to the TIMM library? Also, I would like to know what modifications I need to make in order to run it successfully. I look forward to your response.

**Comment by Lutong-Qin** [comment]
![image](https://github.com/Lab-LVM/imagenet-models/assets/51037385/6eb22fde-3487-4640-ad39-9395fd1d9c6b)

**Comment by JongbinRyu** [comment]
Hi, thank you for your interest. ga_convnext has to be imported.
Put the import code in the train.py of your TIMM codebase. 
import ga_convnext
